### ISSUE TITLE
Add tool to generate infinite product states

### ISSUE THREAD

**Issue by jesse-osborne** [mptoolkit/mptoolkit#5]
The current workaround is to find a Hamiltonian which has the desired state as its ground state, and use `mp-idmrg-s3e` to find the ground state, but you will generally need to add a perturbation to the Hamiltonian to stop it from getting stuck in a local minimum, and gradually decrease the bond dimension to 1. But this method is annoying and sometimes difficult to get to work properly.

Another possible solution is to use `mp-random` to generate a random product state and then use `mp-iapply` to transform it to the desired state. But `mp-iapply` only works with operators with a trivial quantum number shift across the unit cell, so this doesn't work well if you have have, e.g., U(1) particle number symmetry and want to create an initial state with a certain particle configuration.

An ideal solution would be to have a tool which can generate infinite product states. But I have no idea on a good way to specify the state to the tool.

An easier option would be add the ability to `mp-iapply` to apply operators with a nontrivial quantum number shift, which shouldn't be too hard(?), at least for Abelian symmetries.

**Comment by ianmccul** [comment]
There is an old tool `mp-construct`, for finite wavefunctions, but the syntax is cumbersome.  This should be updated, so that we can write eg
`mp-construct -l lattice -o psi up,down`
to create a Neel state, for example.  The complicated syntax in the old tool mostly comes from non-abelian symmetries, but I can think of some better ways of doing that.  Basically, it needs a quantum number on each bond so we can add a syntax for that, to distinguish a quantum number from a state label.  perhaps something like q:  ?  So eg the AKLT state would be (assuming the state label of the spin is '1') would be q:0.5,1,q:0.5.

**Comment by ianmccul** [comment]
Yes mp-iapply should be able to handle constructing states that have quantum numbers.  This is something I overlooked.  The blocker for this is that the ProductMPO assumes that it is a scalar (basically it is intended to be a unitary), so it doesn't allow operators such as prod_unit(CH(0)).  I think that wouldn't be too hard to fix though.

**Comment by ianmccul** [comment]
> There is an old tool `mp-construct`, for finite wavefunctions, but the syntax is cumbersome. This should be updated, so that we can write eg `mp-construct -l lattice -o psi up,down` to create a Neel state, for example. The complicated syntax in the old tool mostly comes from non-abelian symmetries, but I can think of some better ways of doing that. Basically, it needs a quantum number on each bond so we can add a syntax for that, to distinguish a quantum number from a state label. perhaps something like q: ? So eg the AKLT state would be (assuming the state label of the spin is '1') would be q:0.5,1,q:0.5.

With the complication that quantum numbers can have commas in them.  So maybe use colon as a delimiter, and some other syntax to distinguish a quantum number from a state label?

**Comment by ianmccul** [comment]
How about brackets to distinguish a quantum number?  So eg AKLT state would be (0.5)1(0.5)

**Comment by jesse-osborne** [comment]
I've started trying to write to tool now. Would it make sense to have two different syntaxes, depending on whether the symmetry is non-Abelian or not? So you could specify the state in terms of the local basis states at each site for Abelian lattices, e.g. `1:0:1:0`, and for non-Abelian lattices, you specify the quantum numbers at the bonds as well, like you said earlier, e.g. `(0.5)1(0.5)`.

What I'm unsure about is how you can specify local states which are not in the local basis. For example, if you had a spin chain without symmetries where the local basis is the eigenbasis of $S^z$, how would you be able to specify that you want one of the eigenstates of $S^x$?

**Comment by ianmccul** [comment]
that would work.  But I'd allow both, and treat ":" as equivalent to "(q)", where q is whatever quantum number is needed at that bond.

An alternative would be to use whitespace as a separator, so it would be `1 0 1 0`.  Or maybe allow both; any whitespace or ':' is a separator, and it is optional if there is no ambiguity.  So a separator would be any amount of whitespace, optionally followed by a colon and more whitespace.  We probably should also enforce that local basis labels can't contain whitespace, colons or brackets.

Specifying states that are not local basis states sounds too complicated.  You could do it afterwards with a rotation anyway, eg rotate by pi/2 around the y axis to rotate z into x, with `mp-(i)apply`

**Comment by ianmccul** [comment]
I had some more thoughts on this.  Where there is no ambiguity it would be good to allow strings of local basis states that have no separator.  For example, in a qubit basis of 1 and 0, we could construct a state from a bit string of `1011000101` or whatever.  even `updownupupdowndown` etc has no ambiguity, although it looks pretty ugly and in practice I'd probably write it as `up down up down` or `up:down:up:down` etc.

**Comment by ianmccul** [comment]
For the implementation, perhaps an approach would be to have sparse arrays (i.e. a map), one for the quantum numbers, and one for the local basis states (probably as strings).  Parse the input string and keep track of the current site / bond number.  At the end, go back and fill in the missing quantum numbers / basis states, and flag an error if there is any ambiguity.  Perhaps a good way to do some error diagnosis would be to store the location in the string of each element (so instead of a quantum number, it is something like a `tuple<QuantumNumber, int>` with the int being the character position of the start of the quantum number).

**Comment by ianmccul** [comment]
Possibly we want to use a different type of bracket to represent a quantum number.  The reason is, states that have non-trivial braiding, the brackets make a difference.  eg for semions, `|(ss)s> = -|s(ss)>`, even though they have the same quantum number representation at each bond.  But it is a choice of which brackets we use; I don't mind if we used something like `{ss}s` to bracket anyons, and use `()` for quantum numbers.  Using mp-construct to make non-abelian states is going to be quite rare.  It certainly isn't worth worrying about in the first version.

**Comment by jesse-osborne** [comment]
All of that sounds good, but I'm not very confident in writing parsers, so it would probably take me quite a while to write a parser which can handle a wide range of possible user input.

For the moment, I will just write a basic version which only works with input using colons (`1:0:1:0`) or brackets (`(0.5)1(0.5)`), but not both.

Later, I or someone else can write a more advanced version which can handle more flexible user input and non-Abelian anyons.
