### ISSUE TITLE
Memory issue in mp-excitation-ansatz and related tools

### ISSUE THREAD

**Issue by jesse-osborne** [mptoolkit/mptoolkit#50]
This bug was originally introduce in https://github.com/mptoolkit/mptoolkit-dev/commit/e7999b11d83998765298e71b8c769b3b4725b549, where `mp-excitation-ansatz` was refactored to use the EFMatrix class to handle calculation of the effective Hamiltonian. Now, when the effective Hamiltonian functor is passed to the ARPACK wrapper, mysterious memory issues will occur. After much testing, I was not able to figure out why this was happening. The workaround is to use the functor once before passing it to the ARPACK wrapper: 
https://github.com/mptoolkit/mptoolkit-dev/blob/5d3078b86495cf866946660da83660425dd0838d/mp/mp-excitation-ansatz.cpp#L255-L258
I haven't had any memory issues with this in place. At this point, I won't spend any more time trying to find a proper solution.
Other tools which also use the EFMatrix class to generate an effective Hamiltonian which is passed to ARPACK (e.g. `mp-ea-dmrg`) are also affected.

**Comment by ianmccul** [comment]
changing line 154 of arpack_wrapper.cc to allocate slightly more memory seems to fix it, `std::vector<std::complex<double>> v(n*(ncv+1));   // arnoldi vectors`

But that is a bit messed up, it shouldn't be necessary to do that.  It is almost certainly coming from the 'invalid write of size 8' that valgrind reports.  ARPACK is overwriting 16 bytes beyond the end of the array, which is the size of one complex number.  Is it possible that there is an off-by-one error in the size?

**Comment by ianmccul** [comment]
I confirmed that it reads exactly one vector too many in the `v` array supplied to ARPACK.  But I don't think that is where the bug is.  I think it is probably in EFMatrix, or maybe HEff.

**Comment by ianmccul** [comment]
Ok, I found the problem.  ARPACK is not thread-safe or re-enterant.  But on the first call to `HEff::operator()`, it calls into a bunch of EFMatrix functions, including `GetHEff()`, which calls into `EFMatrix::GetFSC()` (and others) that ends up in `SolveF()` which get the transfer matrix eigenvectors, `GetTLeft` and `GetTRight`, which if they don't exist they are constructed with `CalculateTEVs()`, which calls `get_transfer_unit_eigenpair()`, which calls ARPACK.

When `HEff::operator()` is called first, then it initializes the transfer matrix eigenvectors and all is good.  But if  `HEff::operator()` is called the first time from inside the ARPACK matrix-vector multiply function then it ends up calling ARPACK a second time, and it doesn't like that.

I think the correct fix is to pre-initialize the required transfer matrix eigenvectors earlier (eg in the constructor?).

It would also be nice to add a flag  so that if ARPACK is called in a re-enterant way then it gives some nice error message rather than seg-faulting randomly as global state of ARPACK is overwritten.

**Comment by ianmccul** [comment]
I added some mutex locking (on the main branch), so it will now deadlock if you attempt to re-enter ARPACK.

**Comment by jesse-osborne** [comment]
>I think the correct fix is to pre-initialize the required transfer matrix eigenvectors earlier (eg in the constructor?).

Yes, the transfer matrix eigenvectors can be initialised earlier. They can't be initialised in the constructor at the moment since the wavefunction components (i.e. the different boundaries and windows) are added in separate methods after the constructor is called. (This is mainly because specifying the wavefunctions in the constructor would have been a hassle: if I can write a new EAWavefunction class which can handle n-particle wavefunctions, then I can make the constuctor require the EAWavefunctions for the bra and ket.)

The EFMatrix class was designed to only calculate the transfer matrix eigenvalues and E-/F-matrix components as they are needed, to remove the hassle of trying to figure out which ones are needed beforehand, and the correct order to calculate them (for the E-/F-matrix components).

Also, if you update part of the wavefunction, e.g. one of the matrices in the window, it will invalidate only the E-/F-matrix components which depend on that, while keeping the unaffected parts, to avoid recalculating them. (There seems to be a problem where you can update the boundaries and it does not invalidate anything: I don't see any use at the moment for wanting to change the boundaries, so I might just make it so you can't do that.)

A potential problem, however, is when you have unitary operators on the diagonal of the MPO, then it will calculate the transfer matrix eigenvectors in `SolveMPO_EA_Left/Right` in `mp-algorithms/triangular_mpo_solver_ea.cpp`. These would also need to be calculated beforehand, but that would require changing a lot of code.

**Comment by ianmccul** [comment]
Maybe add a function to pre-calculate the transfer matrix eigenvectors, or as many as you can given what has already been calculated?  Then you could call that prior to calling ARPACK.
